#ifndef LEST_RENDER_ENGINE_EVENT_HPP
#define LEST_RENDER_ENGINE_EVENT_HPP

namespace lre
{
enum class LestRenderEngineEvents
{
  MOUSE_BUTTON_PRESS,
  MOUSE_BUTTON_RELEASE,
  MOUSE_MOVE,
  KEY_PRESS,
  KEY_RELEASE,
  WINDOW_RESIZE
};
}

#endif